# Generated by Django 5.0.6 on 2024-07-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField(default='')),
                ('q2', models.CharField(choices=[('', 'Select'), ('Bathrooms', 'Bathrooms'), ('Building', 'Building'), ('Other', 'Other')], default='', max_length=20)),
            ],
        ),
    ]
